from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
	path('',views.index, name ='index'),
	path('accounts/files/',views.files,name='files'),
	path('profiles/',views.profs,name='profs'),
	path('acceptingsugg/',views.accepting_sugg,name='home'),
	path('home/',views.home,name='home'),
	path('jobs/',views.jobs,name='jobs'),
	path('successful/<str:name>/payment/',views.pay,name='payment'),		
	path('home/myprojects/',views.myprojects,name='home'),
	path('home/tasks/',views.maintasks,name='maintasks'),
	path('home/tasks/task1/',views.tasks1,name='task1'),
	path('accounts/signup/',views.v_signup,name='v_signup'),
	path('home/<int:project_id>/',views.details,name='details'),
	path('home/<int:project_id>/adddeployers/',views.add_deployers,name='add_deployers'),
	path('home/<int:project_id>/adddeployers/<str:name>/',views.add,name='add_deployers'),
	path('base/',views.base,name='base'),
	path('home/<int:project_id>/createdeployment/',views.profile_deployments,name='profile_deployments'),
	path('successful/',views.successful,name='successful'),
	path('home/<int:project_id>/<int:file_id>/',views.files,name='files'),
	path('home/<int:project_id>/editproject/',views.edit_project,name='edit_project'),
	path('createproject/',views.create_project,name='create_project'),
	path('home/<int:project_id>/createfile/',views.create_file,name='create_file'),
	path('home/<int:project_id>/tasks/<int:task_id>/createtodo/',views.create_todo,name='create_todo'),
	path('home/<int:project_id>/delete/',views.deletep,name='delete_project'),
	path('home/<int:project_id>/<int:file_id>/delete/',views.deletef,name='files'),
	path('home/<int:project_id>/delete/deleteproject/',views.delete_project,name='delete_project'),
	path('home/<int:project_id>/<int:file_id>/delete/deletefile/',views.delete_file,name='files'),
	path('home/<int:project_id>/<int:file_id>/addsuggestion/',views.create_suggestion,name='files'),
	path('home/<int:project_id>/<int:file_id>/viewsuggestions/',views.view_suggestions,name='files'),
	path('home/<int:project_id>/<int:file_id>/viewsuggestions/<int:suggestion_id>/',views.suggestions,name='files'),
	path('home/<int:project_id>/<int:file_id>/viewsuggestions/<int:suggestion_id>/confirmsuggestion/',views.confirm_suggestion,name='files'),
	path('finddeployer/',views.find_deployer,name='successful'),
	path('notifications/',views.notifications,name='notifications'),
	path('successful/<str:name>/',views.profiles,name='successful'),
	path('successful/<str:name>/request/',views.request,name='request'),
	path('successful/<str:name>/request/confirm_request/',views.confirm_request,name='request'),
	path('notifications/deployer/',views.deployer_confirm,name='request'),
	path('finddeployer/subject/', views.subject, name='subject'),
	path('home/<int:project_id>/update/',views.update,name='update'),
	path('home/<int:project_id>/history/',views.history,name='history'),
	path('home/<int:project_id>/back/',views.goback,name='history'),
	path('home/graph/',views.graph, name='graph'),
	path('home/<int:project_id>/createtask/<int:task_id>/next/',views.create_task1,name='create_task1'),
	path('home/<int:project_id>/createtask/<int:task_id>/next/1/',views.create_task2,name='create_task1'),
	path('home/<int:project_id>/createtask/',views.create_task,name='create_task'),
	path('home/<int:project_id>/tasks/',views.tasks,name='tasks'),
	path('home/<int:project_id>/tasks/<int:task_id>/',views.taskdetails,name='taskdetails'),
	path('home/<int:project_id>/tasks/alltasks/',views.alltasks,name='taskdetails'),
	path('home/<int:project_id>/tasks/<int:task_id>/finishtask/',views.finish_task,name='taskdetails'),
	path('home/<int:project_id>/tasks/<int:task_id>/<int:todo_id>/',views.todo_details,name='create_todo'),
	path('home/<int:project_id>/tasks/<int:task_id>/<int:todo_id>/finish/',views.todo_finish,name='create_todo'),
	path('<int:task_id>/createjob/',views.create_job, name='create_job'),	
	path('jobs/<int:task_id>/',views.apply, name='apply'),	
	path('<int:task_id>/',views.view_applications, name='viewapplications'),	
	path('<int:task_id>/<int:application_id>/accept/',views.accept, name='accept'),	
	path('<int:task_id>/<int:application_id>/decline/',views.decline, name='decline'),	
	path('<int:task_id>/<int:application_id>/decline/',views.decline, name='decline'),	
	path('home/<int:project_id>/tasks/<int:task_id>/removefromjob/',views.remove_job,name='remove_job'),
	path('mytasks/',views.mytasks,name='mytasks'),
	path('<int:project_id>/<int:file_id>/changesugg/',views.sugg,name='sugg'),

]

