# Generated by Django 2.0.1 on 2018-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180816_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='no_deployments',
            field=models.IntegerField(default=0),
        ),
    ]
