# Generated by Django 2.0.1 on 2018-08-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180816_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='group',
            new_name='user',
        ),
    ]
