# Generated by Django 2.0.1 on 2018-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180819_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deployer',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
