# Generated by Django 2.0.1 on 2018-08-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180819_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deployment',
        ),
    ]
