# Generated by Django 2.0.1 on 2018-08-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180821_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
