# Generated by Django 2.0.1 on 2018-08-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180823_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='DEFAULT VALUE', upload_to=''),
        ),
    ]
