# Generated by Django 2.0.1 on 2018-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180823_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
    ]
