# Generated by Django 2.0.1 on 2018-08-23 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_project_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dateofcreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 21, 49, 23, 194097)),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
