# Generated by Django 2.0.1 on 2018-08-24 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_auto_20180824_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfile_name', models.CharField(default='DEFAULT', max_length=100)),
                ('sfile', models.TextField(default='DEFAULT')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.File')),
            ],
        ),
    ]
