# Generated by Django 2.0.1 on 2018-08-24 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0032_suggested_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggested_Files',
            new_name='Suggestions',
        ),
    ]
