# Generated by Django 2.0.1 on 2018-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20180824_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
