# Generated by Django 2.0.1 on 2018-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_project_require_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
