# Generated by Django 2.0.1 on 2018-08-25 08:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_suggestion_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=tinymce.models.HTMLField(default='DEFAULT'),
        ),
    ]
