# Generated by Django 2.0.1 on 2018-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20180825_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='description',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='accounts/static'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='sfile',
            field=models.FileField(default='DEFAULT', upload_to=''),
        ),
    ]
