# Generated by Django 2.0.1 on 2018-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20180825_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
