# Generated by Django 2.0.1 on 2018-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180825_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
