# Generated by Django 2.0.1 on 2018-08-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_file_new_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='sfile',
            field=models.FileField(upload_to='accounts/static'),
        ),
    ]
