# Generated by Django 2.0.1 on 2018-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_profile_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subject',
            field=models.CharField(default='DEFAULT', max_length=30),
        ),
    ]
