# Generated by Django 2.0.1 on 2018-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_suggestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
