# Generated by Django 2.0.1 on 2018-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_project_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
