# Generated by Django 2.0.1 on 2018-09-03 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0059_delete_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
