# Generated by Django 2.0.1 on 2018-09-03 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_deployment_deployer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='data',
            field=models.DateField(default=datetime.datetime(2018, 9, 3, 8, 45, 32, 799891, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='deployment',
            name='no_deployments',
            field=models.IntegerField(default=0),
        ),
    ]
