# Generated by Django 2.0.1 on 2018-09-03 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20180903_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='data',
        ),
        migrations.AddField(
            model_name='deployment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 3, 8, 47, 4, 254159, tzinfo=utc)),
        ),
    ]
