# Generated by Django 2.0.1 on 2018-09-03 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20180903_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 3, 9, 5, 19, 97204, tzinfo=utc)),
        ),
    ]
