# Generated by Django 2.0.1 on 2018-09-03 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20180903_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 3, 9, 46, 57, 797700, tzinfo=utc)),
        ),
    ]
