# Generated by Django 2.0.1 on 2018-09-03 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20180903_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dateofcreation',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 3, 10, 30, 40, 826308, tzinfo=utc)),
        ),
    ]
