# Generated by Django 2.0.1 on 2018-09-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_remove_deployment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='DEFAULT', max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
    ]
