# Generated by Django 2.0.1 on 2018-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_profile_newtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_task',
            field=models.BooleanField(default=False),
        ),
    ]
