# Generated by Django 2.0.1 on 2018-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_task_finishtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.IntegerField(default=0),
        ),
    ]
