# Generated by Django 2.0.1 on 2018-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_profile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created at'),
        ),
    ]
