# Generated by Django 2.0.1 on 2018-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_task_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
