# Generated by Django 2.0.1 on 2018-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_project_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deployers',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
