# Generated by Django 2.0.1 on 2018-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_task_deployers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='deployers',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Profile'),
        ),
    ]
