# Generated by Django 2.0.1 on 2018-09-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20180907_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deployers',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
    ]
