# Generated by Django 2.0.1 on 2018-09-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20180907_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='payed',
            new_name='paid',
        ),
    ]
