# Generated by Django 2.0.1 on 2018-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_auto_20180908_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
