# Generated by Django 2.0.1 on 2018-09-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_task_payment_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.TextField()),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Task')),
            ],
        ),
    ]
