# Generated by Django 2.0.1 on 2018-09-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_to_do'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='To_Do',
            new_name='Todo',
        ),
    ]
