# Generated by Django 2.0.1 on 2018-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
