# Generated by Django 2.0.1 on 2018-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
