# Generated by Django 2.0.1 on 2018-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_profile_unfinished_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
