# Generated by Django 2.0.1 on 2018-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20180911_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alltasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='finished_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
