# Generated by Django 2.0.1 on 2018-09-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_file_deployer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='deployer',
        ),
    ]
