# Generated by Django 2.0.1 on 2018-09-12 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0103_auto_20180912_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deployer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
