# Generated by Django 2.0.1 on 2018-09-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0104_file_deployer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='deployer',
        ),
        migrations.AddField(
            model_name='file',
            name='deployer',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
