# Generated by Django 2.0.1 on 2018-09-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_auto_20180912_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='new_suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='new_task',
            field=models.BooleanField(default=False),
        ),
    ]
