# Generated by Django 2.0.1 on 2018-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_auto_20180913_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
