# Generated by Django 2.0.1 on 2018-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_auto_20180913_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search',
            field=models.BooleanField(default=False),
        ),
    ]
