# Generated by Django 2.0.1 on 2018-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20180917_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='DEFAULT', help_text='Skills', max_length=100),
        ),
    ]
