# Generated by Django 2.0.1 on 2018-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_auto_20180917_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
