# Generated by Django 2.0.1 on 2018-09-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='profile',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
