# Generated by Django 2.0.1 on 2018-09-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_reasons_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reasons',
            new_name='Application',
        ),
    ]
