# Generated by Django 2.0.1 on 2018-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20180917_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='new_app',
            field=models.BooleanField(default=False),
        ),
    ]
