# Generated by Django 2.0.1 on 2018-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_application_new_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='suggestions',
            field=models.BooleanField(default=False),
        ),
    ]
